# Generated by Django 3.1.4 on 2022-10-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221001_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desciption',
            new_name='description',
        ),
    ]
